### ISSUE TITLE
Typo in documentation about `options`

### ISSUE THREAD

**Issue by sixclones** [SimeonGriggs/sanity-plugin-iframe-pane#2]
Hello,

According to documentation, `options.refresh` should handles the refresh mechanism but [according to the source file (`src/Iframe.js` L12)](https://github.com/SimeonGriggs/sanity-plugin-iframe-pane/blob/main/src/Iframe.js#L12), the name of the key is `reload`.

**Comment by SimeonGriggs** [comment]
Right, this was corrected in the README after it was first [posted to the Exchange](https://www.sanity.io/plugins/iframe-pane)

This should be updated now there as well.
