### ISSUE TITLE
postMessage on changes

### ISSUE THREAD

**Issue by homerjam** [SimeonGriggs/sanity-plugin-iframe-pane#4]
Hello,

Could this plugin be adapted to use [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) so that the preview site could listen for changes?

**Comment by SimeonGriggs** [comment]
It's possible, however that's not an API I'm familiar with personally. Without a solid use-case it's unlikely I'll get the time to add it soon.
