### ISSUE TITLE
Frame displays compactedly on initial load

### ISSUE THREAD

**Issue by mitchuman** [SimeonGriggs/sanity-plugin-iframe-pane#6]
Frame displays compactly on initial load. Requires to toggle the responsive button to fix the sizing.

<img width="356" alt="Screen Shot 2022-08-25 at 2 03 02 PM" src="https://user-images.githubusercontent.com/73133191/186768945-71df9e11-2485-4bbd-b0b6-db44d18e0ce4.png">

(Blacking out to conceal data, but the sizing of the frame is as shown)

**Comment by SimeonGriggs** [comment]
Believe this is a bug that was quickly resolved in a previous version – can you upgrade to latest and confirm the same behaviour?
